### ISSUE TITLE
See Also: Encoding::FixLatin and clarify difference of scope

### ISSUE THREAD

**Issue by jonassmedegaard** [theory/encode-zapcp1252#4]
As I understand it, Encode::ZapCP1252 handles Latin-1 text with gremlins.  If throwing a UTF-8 text at it, it will happily rip proper UTF-8 characters aparts, because it expects the whole string - not only the gremlins - to be improperly tagged as UTF-8.

Seems Encoding::FixLatin covers a similar but slightly different situation: UTF-8 text with gremlins.

Or put differently, seems to me that Encode::ZapCP1252 is the aggressive tool and Encoding::FixLatin is the cautious one, in the context of UTF-8 texts.

I suggest mentioning the existence of Encoding::FixLatin and clarify the difference.

**Comment by theory** [comment]
Hi @jonassmedegaard: Encode::FixLatin no longer appears on CPAN. Examples:

* https://metacpan.org/release/Encode-FixLatin
* https://metacpan.org/search?q=Encode%3A%3AFixLatin

Do you know what became of it? Renamed, perhaps?

**Comment by jonassmedegaard** [comment]
Hi David,

Quoting David E. Wheeler (2019-11-24 20:20:29)
> Hi @jonassmedegaard: Encode::FixLatin no longer appears on CPAN. Examples:
> 
> * https://metacpan.org/release/Encode-FixLatin
> * https://metacpan.org/search?q=Encode%3A%3AFixLatin
> 
> Do you know what became of it? Renamed, perhaps?

Not sure if _ever_ named Encode-FixLatin - the module I ended up 
packaging for debian was Encoding::FixLatin which is stil there: 
https://metacpan.org/release/Encoding-FixLatin

Hope that helps, and sorry for the late response,

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by khwilliamson** [comment]
Actually,  Zap is not a subset of FixLatin.  In one mode, Zap will substitute ASCII strings to simulate characters not representable in Latin1.  In the other mode, what happens depends on if my PR is accepted or not.  If it is, it would convert properly encoded UTF-8 that represents the code points that CP1252 defines but which will never really be in real UTF-8 text into the UTF-8 for the CP1252 definitions.  If the PR isn't accepted, something else needs to be done, as it currently can corrupt legal UTF-8.

In reading the man page for FixLatin, there is an oversight.  It talks about pairs of BB characters, but there can be triplets and quadruplets as well.  For those, this statement in the doc doesn't apply 

"If you look those ranges up on a Latin-1 code chart you'll see that the first character would need to be an uppercase accented letter and the second would need to be a non-printable control character or a special punctuation symbol."

Pod::SImple has the task of trying to figure out if input text is legal CP1252 vs legal UTF-8.  It now does quite a good job at that.  One technique it uses that is only recently available in Perl is checking that the text is all from the same script, namely Latin, using the new script run feature in pattern matching.  That means it can successfully get that Muvrarášša isn't 1252 (a Sami word for a mountain in Norway), which it couldn't before.

**Comment by khwilliamson** [comment]
I mentioned the script run feature as something to keep in mind for extending these modules.  Pod::Simple also uses some other techniques.  For example, if the sequence interpreted as UTF-8 forms a character in a litttle used script, such as IPA or braille, it likely was CP1252; and if the characters wasn't in the very first version of Unicode, it is likely to be CP1252, as that release covered just about all characters in common use in modern languages likely to be used in pod.

**Comment by theory** [comment]
> Not sure if _ever_ named Encode-FixLatin - the module I ended up
> packaging for debian was Encoding::FixLatin which is stil there:
> https://metacpan.org/release/Encoding-FixLatin

And that's what you called it here, too. Good grief, sorry, I somehow misread it all those years ago. Sheesh. Will fix before the next release.

**Comment by jonassmedegaard** [comment]
Ah, indeed. And I am guilty of totally missing that as well (I remember double-checking when you closed this issue).

Cool that it gets corrected now, at least :-)
